# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f7b1e376dddc573f77c4518ce362d958e0a0e2ea3503939d95f94d63b49529ab6068bc345638afa572c562685355abc785486a2e65e8eb8f0b2c9ff00022774

test:
  secret_key_base: ef3431e15c63624cefbf33447cd9960def1d245c39bc21f876b093795f4c6d50600d2b32d3270ef66f3501747ea41c83ca5f1a9a875284b49ca10cc7eb516432

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
